### ISSUE TITLE
Investigate other nationally representative samples for expenditure measurement

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/Lotteries#10]
The goal of this issue is to understand whether we want to use some other high-quality nationally representative sample survey to measure expenditures.
* UAS: https://uasdata.usc.edu/index.php. @dtaubinsky will contact.
* ALP: https://alpdata.rand.org. @jackblun  will contact.

**Comment by dtaubinsky** [comment]
I sent Anya an email asking about UAS. 

One further thought: The nice thing about UAS is that it has a bunch of cognitive ability and financial literacy measures, and probably already has some risk aversion measures as well. These all come for free. I don't think TESS has these.

However, UAS is more expensive: https://uasdata.usc.edu/index.php

However, running just 3 questions (which are considered 1 minute), would cost <10k for 3 thousand people. So we could consider UAS as a useful supplement if want wanted to correlate lottery expenditures with a rich set of cognitive ability and financial literacy questions, as well as enlarge the dataset on lottery expenditures by income.

**Comment by dtaubinsky** [comment]
Here is the UAS response:

_Sorry for the delay! Hi Dmitry! We have a couple of options; if you are flexible about timing and not adverse to having your questions in an omnibus with other topics, the prices are as follows: https://uasdata.usc.edu/page/Omnibus+Pricing+Calculator

If you have a more complicated survey, then stand alone makes the most https://uasdata.usc.edu/page/Pricing+Calculator

I would be glad to discuss this if you are around today.

Tania_

**Comment by bblockwood** [comment]
Thanks! Omnibus sounds like it would work for us, though it's still not that cheap. The cost of 8 simple questions is $8333.

**Comment by jackblun** [comment]
Response from ALP:
"
Apologies for the delayed reply and thank you for your interest in the ALP.    You can certainly field a survey questionnaire to our ALP.  A summary of the steps and standard ALP pricing is here: https://www.rand.org/labor/alp/run-survey/ten-steps.html   Once we have information about your sample, desired number of completions and the length of your survey we can quickly get you a cost estimate.   Then if you'd like to proceed, we can get a contract agreement in place and get to work.   After signing a contract, it takes about 4 weeks to get the survey into the field and you can get most of your responses within a week and all likely within a month or two.
"
Looking at the link here, an example of pricing is:
"
- First 500 survey completions x # of survey minutes x $3.00
- Next 500 survey completions x # of survey minutes x $2.50
- Remaining survey completions x # of survey minutes x $2.00
- Fixed fee $2000 to cover server costs and administration
So, for example, 1,500 respondents taking a 10-minute interview would cost $39,500.
"

**Comment by huntallcott** [comment]
I'm closing this while we wait to hear from TESS. Presumably if we get TESS then we won't use these.
