### ISSUE TITLE
Changes in Ticket Prices

### ISSUE THREAD

**Issue by anjoung** [huntallcott/Lotteries#18]
I will be compiling in this issue any updates on changes to the price of Megamillions, Powerball, or other lottery tickets.

**Comment by anjoung** [comment]
Have reached out to Texas, Florida, North Carolina, and Connecticut about whether there has been any change.

North Carolina responded that its ticket price for Cash 5 has always been $1.

**Comment by anjoung** [comment]
The cost of a CT lotto ticket has remained unchanged from $1 since 1983.

**Comment by bblockwood** [comment]
@anjoung still hoping to hear back from a couple states about this, but closing this issue for now.
