### ISSUE TITLE
Change in Payout Structure or Drawing Probabilities 

### ISSUE THREAD

**Issue by anjoung** [huntallcott/Lotteries#19]
I will be compiling in this issue any information regarding changes in payout structure or drawing probabilities for Megamillions, Powerball, or any other lottery.

**Comment by anjoung** [comment]
Have reached out to Texas, Florida, North Carolina, and Connecticut about whether there has been any change.

**Comment by anjoung** [comment]
North Carolina just sent me the following. The change occurred on Nov. 4th, 2018.

![north carolina - cash 5](https://user-images.githubusercontent.com/30239050/50304500-1eb31300-045e-11e9-958c-54533c479c30.jpg)

**Comment by anjoung** [comment]
CT sent us information on changes to the pay structure, ticket cost, and names for their state lotto.

**Comment by anjoung** [comment]
I just received pay structure data from Florida. That means that we have prize structure data from Powerball, CT, FL, and NC.

**Comment by bblockwood** [comment]
Closing this issue for now, though can reopen if there are other data-gathering opportunities here.
