### ISSUE TITLE
Set up MTurk survey 

### ISSUE THREAD

**Issue by bblockwood** [huntallcott/Lotteries#25]
The goal of this issue is to prepare everything necessary for launching the lotteries survey on MTurk, including the following:

1. Obtain IRB approval/exempt status, through a "blanket" IRB request. 
2. Request fund matching through Wharton Behavioral Lab. 
3. Prepare task for launch on TurkPrime (probably?) and pre-load funds.

**Comment by anjoung** [comment]
@bblockwood Will I be taking the lead on writing the IRB report?

**Comment by bblockwood** [comment]
Thanks for the quick follow-up! Yes, but I’d like to do it as a “blanket IRB request” which will cover this and an open-ended range of other potential MTurk studies that could be run in the future. Hold off for the moment and I’m planning to get you an example of such a request by early next week.

**Comment by bblockwood** [comment]
@rajbhargava would you be up for shepherding the actual launch of the MTurk survey now? If so, I believe the Qualtrics component is ready to go, and just needs to be embedded in a an MTurk HIT. I understand from @huntallcott that there is an MSR MTurk account that can be used for this. There is a useful guide [here](https://blog.mturk.com/getting-great-survey-results-from-mturk-and-qualtrics-be1704ff9786). If you have capacity, it could be very helpful if you take a look at that and then try running a "pilot pilot" with just 10 people or so, to make sure everything works. (Then we can run with a larger pilot sample, like 100 or 200.) Thanks in advance, and let us know if you have any questions?

**Comment by bblockwood** [comment]
A quick update on this: a small pilot (~20) is currently running on MTurk. Provided everything looks reasonable, I'll collect another ~100 responses this weekend, so that we can begin analyzing the data next week.

**Comment by bblockwood** [comment]
Closing this issue, as the MTurk implementation is done, IRB approved, etc. It's just a matter of cleaning and analyzing the data now in #29.
