### ISSUE TITLE
Clean up dropbox and GitHub repo

### ISSUE THREAD

**Issue by huntallcott** [huntallcott/Lotteries#28]
The goal of this is to make sure the dropbox folder and GitHub repo are organized, now that @rajbhargava is joining the project.

@rajbhargava is an organization freak (he inherited this from Matt Gentzkow), and he will explode if we don't stay organized.

cc @anjoung @bblockwood @dtaubinsky 

#### GitHub
I have just re-organized the GitHub repo.
* I changed the organization so that we have functional directories, e.g. /build/ and /analysis/, each with input, code, and output directories, instead of the Code and Output directories. All the code is where you would expect it to be, just in this new organization. I hope this is OK. This follows the GSLab approach which we are trying to implement broadly. 
* I deleted the temp-Hunt folder. Andrew, ideally you could avoid folders like that as well. Sorry for setting a bad example. All code in that folder could go in an Issues/ subfolder if it's for an issue, or delete it if it's legacy, or put it in the build or analysis directories if you're actually using it.
* Andrew can you take a look at the GitHub repo and make sure that there are not extra/old files there?

#### Dropbox
1. I renamed dropbox/Externals to dropbox/data, and subfolders input and intermediate, in keeping with the naming conventions that we're trying to use across multiple projects. @anjoung can you make sure this works in the code? Sorry for the change but I think it's easy to change the external folder location call. (Incidentally, in SetGlobals.do we should set the global external path to refer to dropbox/Lotteries/Data, not just dropbox/Lotteries/.) 
2. In general we are making too much use of the /Notes/ folder. I moved Surveys to a Surveys folder and IRB to an IRB folder. @anjoung it looks like there are a bunch of data prep notes:
   - For messy data prep notes, perhaps you could put them in /dropbox/Notes/DataCleaning. 
   - Actual data for the analysis (e.g. Game classification.xlsx) should go in dropbox/Data/
   - For your polished overview of the data that you are finishing for #22, I'd put it in dropbox/DataStorageCodebooks/, as it's basically like a codebook.
3. @anjoung I see a lot of "conflicted copies" in dropbox/Data/intermediate. In general can you keep track of these and delete them?
4. In general as you (@anjoung) are cleaning up the LaFleur's data pipeline over the next week can you delete old files that are not needed? Some of these are quite old.

Thanks. Sorry that @rajbhargava is so focused on organization :-), but I think I agree that this in the long run is going to be important, especially as Andrew moves off the project over the next 8 weeks.

**Comment by anjoung** [comment]
Will get to work on this first thing tomorrow. Looking forward to working with @rajbhargava !

**Comment by anjoung** [comment]
**GitHub**

- All the code has been altered to conform to the new GitHub and Dropbox structure
- Removed my temp file. Added it into the Issues subfolder or deleted the code if it was old and not a useful reference.
- There is "simulations" subfolder, which contains stuff that I cannot open. The word "simulations" makes it seem important, so I didn't touch it but please let me know if it should just be removed. 

**Dropbox**
- I removed most of the data prep notes, since most were just older versions of the polished version
- Created an archive subfolder in the notes folder. This subfolder contains notes that I felt might be useful for reference and wasn't comfortable with deleting.
-  Re-organized Dropbox and added a few more read me files.

Please let me know if anything remains unaccounted! @rajbhargava feel free to shoot me any questions or further suggestions to improve organization.

**Comment by huntallcott** [comment]
Great. I have one other request: sometimes there are problems with having file paths with spaces or weird characters, e.g. "Lottery+Sales Data". Can you rename this something else, e.g. LotterySalesData or lottery_sales_data? 
Otherwise I think this is good progress and OK to close this issue unless @rajbhargava or @bblockwood has other thoughts.

Thanks again for indulging me on this. I think it really helps.

**Comment by bblockwood** [comment]
I agree with @huntallcott, with a minor amendment: please also avoid underscore characters in file paths. Lyx doesn’t properly escape them when they’re inserted inline in math mode. Once those are renamed, @anjoung can you please close this issue? 

Thanks!

**Comment by anjoung** [comment]
Done! Spaces remain for "input" filepaths, but we should not be pulling anything into Lyx from the input files (i.e., raw data).
