### ISSUE TITLE
Draft abstract

### ISSUE THREAD

**Issue by bblockwood** [huntallcott/Lotteries#30]
Goal is to agree on a draft of the abstract, for submission to conferences.

**Comment by bblockwood** [comment]
I have taken a crack at a draft [here](https://docs.google.com/document/d/14JQbhHE38DOkHsFXYIIelfGklfRB9zGWPTpr3DmlmJU/edit#). (in gdocs for comments/edits, but then I'll paste into the paper draft.) @huntallcott, @dtaubinsky, suggest any edits or add comments if you like?

Then if you're ok with it, I'll submit this to NTAs for presentation in November. (Current abstract is low stakes — I'm one of the behavioral organizers.)

**Comment by bblockwood** [comment]
Sorry sharing was incorrectly set on the gdoc -- fixed now.

**Comment by huntallcott** [comment]
Looks great to me; thanks.

**Comment by dtaubinsky** [comment]
Yes, looks great! Thanks @bblockwood!
