### ISSUE TITLE
NYU IRB for Main Survey

### ISSUE THREAD

**Issue by rajbhargava** [huntallcott/Lotteries#34]
The goal of this issue is to complete the NYU IRB for the main survey.

**Comment by huntallcott** [comment]
@rajbhargava we are close enough on this survey -- can you go ahead and put the IRB through ASAP so that we have it ready for when Wharton gives us the green light? 
Thanks so much.

**Comment by rajbhargava** [comment]
@huntallcott IRB has been routed to you for approval!

**Comment by rajbhargava** [comment]
@bblockwood: NYU IRB has approved the survey. I've uploaded the materials to Dropbox, you can start the Penn/Wharton IRB!

**Comment by bblockwood** [comment]
@rajbhargava thanks! I have a blanket IRB approval that covers unincentivized experiments like this — the approval letter is on Dropbox now.
