### ISSUE TITLE
Scrape CA lottery data

### ISSUE THREAD

**Issue by bblockwood** [huntallcott/Lotteries#37]
The goal of this issue is to web scrape data from the CA lottery website for PowerBall, MegaMillions, and SuperLotto, as far back in time as feasible.

**Comment by afras-sial** [comment]
@bblockwood The files are uploaded and the output data files are in the Dropbox. 

- For Powerball, we go back to April 10, 2013 (first draw after CA joined)
- For Mega Millions, we go back to June 24, 2005 (first draw after CA joined)
- For SuperLotto Plus, we go back to September 10, 2003 (limit of data availability)

**Comment by bblockwood** [comment]
@afras-sial you are awesome! Closing this issue for now -- can reopen if there's anything else that comes up related to it.
